/**
 * One Party. Many Reasons. — order intake.
 *
 * Paste this into the Apps Script editor of the Google Sheet that holds your
 * guest list (Extensions -> Apps Script), then deploy it as a Web App.
 * Full instructions are in README.md.
 *
 * This is the only place the 100-ticket limit is enforced. Anything in the
 * website's own JavaScript can be edited by whoever is visiting the page.
 */

/* ============================ Settings ============================ */

/** Tab in the spreadsheet that holds the orders. */
const SHEET_NAME = 'Orders';

/** Hard capacity of the party. Nothing gets written past this. */
const MAX_TICKETS = 100;

/** Price per ticket, in euro. Must match TICKET_PRICE in js/config.js. */
const TICKET_PRICE = 10;

/** Most tickets allowed in a single order. Must match MAX_PER_ORDER in js/config.js. */
const MAX_PER_ORDER = 10;

/** Column layout of the Orders sheet, 1-indexed. */
const COLUMN = {
  TIMESTAMP: 1,
  ORDER_ID: 2,
  NAME: 3,
  EMAIL: 4,
  TICKETS: 5,
  DONATION: 6,
  TOTAL: 7,
  STATUS: 8,
  NOTES: 9,
};

const HEADERS = [
  'Timestamp', 'Order ID', 'Name', 'Email',
  'Tickets', 'Donation (EUR)', 'Total (EUR)', 'Status', 'Notes',
];

/** Status values. Anything other than 'cancelled' counts against capacity. */
const STATUS = {
  RESERVED: 'reserved',
  PAID: 'paid',
  CANCELLED: 'cancelled',
};

/* ============================ Entry points ============================ */

/**
 * Handles an order from the website.
 *
 * Request body is JSON (sent as text/plain so the browser skips the CORS
 * preflight that Apps Script cannot answer):
 *   { quantity, donation, name, email, honeypot, orderId? }
 *
 * The orderId is generated by the browser and shown to the guest before this
 * runs. If we have seen it before, that row is updated; if not, a row is added.
 *
 * Responds with { ok: true, orderId } or { ok: false, reason }, where reason is
 * one of: 'invalid', 'sold_out', 'not_enough', 'busy'.
 */
function doPost(request) {
  if (!request || !request.postData || !request.postData.contents) {
    return jsonResponse({ ok: false, reason: 'invalid' });
  }

  var payload;
  try {
    payload = JSON.parse(request.postData.contents);
  } catch (error) {
    return jsonResponse({ ok: false, reason: 'invalid' });
  }

  // Bots fill in the hidden field; humans never see it.
  if (payload.honeypot) {
    return jsonResponse({ ok: false, reason: 'invalid' });
  }

  var order = validateOrder_(payload);
  if (!order) {
    return jsonResponse({ ok: false, reason: 'invalid' });
  }

  // Serialise everything below, so two people cannot both claim the last seats.
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(15000)) {
    return jsonResponse({ ok: false, reason: 'busy' });
  }

  try {
    return jsonResponse(saveOrder_(order, payload.orderId));
  } finally {
    lock.releaseLock();
  }
}

/** Lets you check in a browser that the deployment is live. */
function doGet() {
  return jsonResponse({ ok: true, service: 'One Party. Many Reasons. — order intake' });
}

/**
 * Run this once from the editor to create the Orders tab with its header row.
 * Safe to run again later; it will not touch existing rows.
 */
function setup() {
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = spreadsheet.getSheetByName(SHEET_NAME) || spreadsheet.insertSheet(SHEET_NAME);

  sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]).setFontWeight('bold');
  sheet.setFrozenRows(1);
  sheet.getRange(1, COLUMN.TIMESTAMP, sheet.getMaxRows()).setNumberFormat('yyyy-mm-dd hh:mm');
  sheet.autoResizeColumns(1, HEADERS.length);
}

/* ============================ Internals ============================ */

/**
 * Checks and normalises an incoming order.
 * @return {?Object} the clean order, or null if anything is off.
 */
function validateOrder_(payload) {
  var quantity = Number(payload.quantity);
  if (!isFinite(quantity) || quantity !== Math.floor(quantity)) return null;
  if (quantity < 1 || quantity > MAX_PER_ORDER) return null;

  var donation = Number(payload.donation);
  if (!isFinite(donation) || donation < 0 || donation > 10000) return null;
  donation = Math.round(donation * 100) / 100;

  var name = String(payload.name || '').trim();
  if (name.length < 2 || name.length > 100) return null;

  var email = String(payload.email || '').trim();
  if (email.length > 150 || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return null;

  return {
    quantity: quantity,
    donation: donation,
    name: name,
    email: email,
    total: Math.round((quantity * TICKET_PRICE + donation) * 100) / 100,
  };
}

/**
 * Writes the order, either as a new row or as an update to an existing one.
 * Assumes the caller holds the script lock.
 */
function saveOrder_(order, existingOrderId) {
  var sheet = getOrdersSheet_();
  var rows = readRows_(sheet);

  // The browser generates the reference and shows it to the guest before we
  // ever hear about it, so an id we have not seen is normal — it means a new
  // row. An id we HAVE seen means the same guest submitting twice, which
  // updates their row instead of adding a second one.
  var requestedId = isValidOrderId_(existingOrderId) ? existingOrderId : '';

  var targetIndex = requestedId ? findRowIndex_(rows, requestedId) : -1;
  if (targetIndex !== -1) {
    // Already paid for: leave the row alone rather than reopening it.
    if (String(rows[targetIndex][COLUMN.STATUS - 1]).toLowerCase() === STATUS.PAID) {
      return { ok: true, orderId: requestedId };
    }
  }

  // Everything that still counts against capacity, ignoring the row we are
  // about to overwrite.
  var sold = 0;
  for (var i = 0; i < rows.length; i++) {
    if (i === targetIndex) continue;
    if (String(rows[i][COLUMN.STATUS - 1]).toLowerCase() === STATUS.CANCELLED) continue;
    sold += Number(rows[i][COLUMN.TICKETS - 1]) || 0;
  }

  if (sold >= MAX_TICKETS) {
    return { ok: false, reason: 'sold_out' };
  }
  if (sold + order.quantity > MAX_TICKETS) {
    return { ok: false, reason: 'not_enough' };
  }

  if (targetIndex === -1) {
    // Fall back to our own reference only if the browser did not supply a
    // usable one (someone posting to this endpoint by hand, for instance).
    var orderId = requestedId || generateOrderId_(rows);
    sheet.appendRow(buildRow_(order, orderId, new Date()));
    return { ok: true, orderId: orderId };
  }

  // +2: rows[] is zero-based and skips the header row.
  var sheetRow = targetIndex + 2;
  var timestamp = rows[targetIndex][COLUMN.TIMESTAMP - 1] || new Date();
  sheet.getRange(sheetRow, 1, 1, HEADERS.length)
       .setValues([buildRow_(order, requestedId, timestamp)]);
  return { ok: true, orderId: requestedId };
}

function buildRow_(order, orderId, timestamp) {
  return [
    timestamp,
    orderId,
    order.name,
    order.email,
    order.quantity,
    order.donation,
    order.total,
    STATUS.RESERVED,
    '',
  ];
}

function getOrdersSheet_() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME);
  if (!sheet) {
    throw new Error('No sheet named "' + SHEET_NAME + '". Run setup() once from the editor.');
  }
  return sheet;
}

/** All data rows, header excluded. */
function readRows_(sheet) {
  var lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];
  return sheet.getRange(2, 1, lastRow - 1, HEADERS.length).getValues();
}

/** Guards against junk in the orderId field ending up in the Sheet. */
function isValidOrderId_(orderId) {
  return typeof orderId === 'string' && /^RT-[A-Z2-9]{4,8}$/.test(orderId);
}

function findRowIndex_(rows, orderId) {
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][COLUMN.ORDER_ID - 1]) === orderId) return i;
  }
  return -1;
}

/**
 * A short, human-readable reference, e.g. RT-7Q4K.
 * The alphabet leaves out characters people mistype (0/O, 1/I).
 */
function generateOrderId_(rows) {
  var alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  for (var attempt = 0; attempt < 50; attempt++) {
    var code = '';
    for (var i = 0; i < 4; i++) {
      code += alphabet.charAt(Math.floor(Math.random() * alphabet.length));
    }
    var candidate = 'RT-' + code;
    if (findRowIndex_(rows, candidate) === -1) return candidate;
  }
  throw new Error('Could not generate a unique order id.');
}

function jsonResponse(payload) {
  return ContentService
    .createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}
